### ISSUE TITLE
Error: Invalid or corrupt jarfile xxxx/PredictionIO-0.9.4/sbt/sbt-launch-0.13.7.jar

### ISSUE THREAD

**Issue by ecoron** [PredictionIO/PredictionIO#131]
after installing from source and starting building an engine  i discovered the error:
```
Error: Invalid or corrupt jarfile xxxx/PredictionIO-0.9.4/sbt/sbt-launch-0.13.7.jar
```
and the build fails.

after some research i found the bug.
it comes from PredictionIO-0.9.4/sbt/sbt-launch-lib.bash (line 40-41)
there are 2 URL's defined  to download the sbt-launch.jar

it seems both urls are outdated and returns a 404 error.

workaround that works for me:

```
cd PredictionIO-0.9.4/sbt
wget http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.7/sbt-launch.jar
mv sbt-launch.jar sbt-launch-0.13.7.jar
```

**Comment by dszeto** [comment]
Thanks for reporting. We will take a look and update the SBT launcher to the latest version.

**Comment by onibox** [comment]
Found the problem: URL1 in sbt-launch-lib.bash returns a 404, but curl only looks into getting some answer from the web server. You need to add the '-f' flag to the curl call.

**Comment by dszeto** [comment]
For the record, we have fixed the problem in 0.9.4 binary distribution to include the `sbt-launch-0.13.7.jar`. The manual fix is here: https://groups.google.com/d/msg/predictionio-user/fllCh8n-0d4/eZ5jnGf71lgJ

Thanks for the suggestion! The upstream launcher has been updated and we will see if they have fixed it.

**Comment by onibox** [comment]
@dszeto Thx for the info regarding 0.9.4! :+1:

**Comment by pferrel** [comment]
Is this the same as the write permission for initial/install download of SBT? 

Closing since this is fixed and include a workaround

**Comment by niebnieb** [comment]
Thanks for the workaround, but 0.9.5 still has the same problem.
btw, I had to change the HBase version in install.sh from 1.0.0 to 1.0.1.1 (not in repository).

**Comment by moein7tl** [comment]
Thanks for issue, but I've the same problem in 0.10.0
