### ISSUE TITLE
Add better error reporting to pio import

### ISSUE THREAD

**Issue by pferrel** [PredictionIO/PredictionIO#137]
catch parsing errors when importing in parallel from text/json or other file types. Often a single malformed line will be very difficult to find so log the malformed line before throwing an abort exception.  Consider exception counting for parsing, allow some small number before aborting, this will catch a blank line at the end and simple exceptions.

**Comment by pferrel** [comment]
comment from @k4hoo 

can add try catch {} block for read[Event](_) to catch any error when convert the json string to event and print message of the error json string

https://github.com/PredictionIO/PredictionIO/blob/develop/tools/src/main/scala/io/prediction/tools/imprt/FileToEvents.scala#L88

**Comment by schon** [comment]
Is anyone working on this issue? If not, I would like to send a PR

**Comment by pferrel** [comment]
No, would love to get a PR. Set it up against the "develop" branch. We are nearing a 0.9.6 release.
