### ISSUE TITLE
PredictionIO - one engine and multiple algorithms

### ISSUE THREAD

**Issue by letrangnhienanh** [PredictionIO/PredictionIO#144]
Can someone help me with this problem, currently I got stuck with one engine and multiple algorithms and need help further.

I have one engine and 2 algorithms, let's call AL1 and AL2. In src/main/scala having 2 algorithm scala files, name AL1Algorithm.scala and AL2Algorithm.scala each algorithm have its own param and model (AL1AlgorithmParams and AL1Model for AL1 and AL2AlgorithmParams and AL2Model for AL2). Therefore there are 2 train functions and 2 predict functions.

I can train 2 algorithms by calling pio train. When I call send_query to test, the program always return the result of the algorithm I put on the top of engine.json file

For instance, if I put AL1Algorithm on top, send_query will run AL1Algorithm "algorithms": [ { "name": "AL1Algorithm", "params": { "n": 100 } }, { "name": "AL2Algorithm", "params": { "n": 100 } }

if I put AL2Algorithm on top, send_query will run AL2Algorithm "algorithms": [ { "name": "AL2Algorithm", "params": { "n": 100 } }, { "name": "AL1Algorithm", "params": { "n": 100 } }

======================================================

My question is, can I call 2 algorithms for one send_query, how to distinguish which algorithm should be call in send_query instead of engine.json. There is something weird here, I think there are problems with my configuration. Will Serving.scala produce results of 2 algorithms at the same time. Can I split the results of each algorithm in serving.

Thank you very much

**Comment by k4hoo** [comment]
just replied in stackoverflow too
http://stackoverflow.com/questions/32604603/predictionio-one-engine-and-multiple-algorithms

Copied and pasted here

You also need to modify the serve() function In Serving.scala. the serve() function has 2 arguments. see below

def serve(query: Query, predictedResults: Seq[PredictedResult]): PredictedResult

The query is sent to both algorithms, and the PredictedResult returned by both algorithms are passed to serve() function as Seq[PredictedResult]. The Seq[] order is the same as the order of algorithm defined in engine.json. You need to modify this to make use of all PredictedResult output by algorithm. Some of the template examples by default only take the 1st result (predictedResults.head)

Please also see "Step 4. Modify Serving to combine multiple algorithms' outputs" in this doc as example.

**Comment by letrangnhienanh** [comment]
Dear Kenneth, 

Can you help me one issue

override def serve(query: Query, predictedResults: Seq[PredictedResult]): PredictedResult = {
            val standard: Seq[Array[ItemScore]] = predictedResults.map(_.itemScores)
            new PredictedResult(standard.flatten.toArray)
}

I can combine the results of 2 algorithms now. Do you have any document about PredictedResult data structure, I would like to split the result.
currently I guess I will base on the index of Seq[Array[ItemScores]]
if I put AL1 before AL2, AL3 then result of AL1 will be before result of AL2, AL3.

If only based on index of Seq[] there can be a risk cause I can change the order of algorithms in engine.json from AL1, AL2, AL3 to AL3, AL1, AL2.

Is there any attribute help me to recognize which result is of what algorithms?
Thank you very much.

**Comment by pferrel** [comment]
I don't think this is the right mechanism to use. why not create two engines and query both, then you know exactly which returned what.

**Comment by letrangnhienanh** [comment]
Dear Pferrel, 
this is because I think with multiple engines approach, if my 5 algorithms using the same data RDD, it is a waste in memory cause data can be duplicated between engines. That is the reason why I want to embed multiple algorithms inside one engine. Currently predictionio did not support that so I already created 5 engines for 5 algorithms. 
Thank you for your information.

**Comment by pferrel** [comment]
ok, makes sense.

BTW: you may want to move the discussion to the dev or user groups, github we use mostly for bugs.
