### ISSUE TITLE
Delete application data in non-interactive mode

### ISSUE THREAD

**Issue by clemp6r** [PredictionIO/PredictionIO#149]
Please provide a way to delete application data without user interaction, so this can be automated (i.e in bash scripts). E.g.:

    pio app data-delete -y MyApp

**Comment by joernroeder** [comment]
I ran into the same issue while running predictionio in a docker container. I've tried to delete data via `docker exec pio app data-delete MyApp` but it stopped at the prompt…

:+1: for `pio app data-delete MyApp -y`

**Comment by clemp6r** [comment]
In fact there is a workaround:

    echo Y | pio app data-delete MyApp

But it's not ideal.

**Comment by pferrel** [comment]
we forced interaction for obvious reasons, thanks for the workaround but may I ask about your use case? Maybe we are missing something more important. For instance we need a way to trim off old events at some point to keep training capped at some max.

Also can we move to the google user group for PIO?

**Comment by clemp6r** [comment]
Sure.

**Comment by pferrel** [comment]
ok, will add to wishlist

**Comment by schon** [comment]
@pferrel 
I also need this option when my batch will be updated. So I have implemented it. 
Could I make a PR on this?

**Comment by pferrel** [comment]
@schon Yes, please create a PR against the develop branch of PredictionIO

Thanks!
