### ISSUE TITLE
Could I change data type of JDBC event table?

### ISSUE THREAD

**Issue by schon** [PredictionIO/PredictionIO#159]
I use mysql as a event table for some reasons.
LEventStore.findByEntity function with entityType and entityId is slow and sometimes I am getting java.util.concurrent.TimeoutException.
I want to create index on this columns to improve performance.

https://github.com/PredictionIO/PredictionIO/blob/65a64c902ad7671dfb2fb0e29d8af806a01c55d0/data/src/main/scala/io/prediction/data/storage/jdbc/JDBCLEvents.scala#L43-L56

So, I modified these columns after creating table in my scripts such as below.

```
alter table pio_event_1_1 modify column entityType varchar(10) not null;
alter table pio_event_1_1 modify column entityId varchar(255) not null;
create index pio_event_1_1_idx1 on pio_event_1_1 (entityId);
create index pio_event_1_1_idx2 on pio_event_1_1 (entityType);
```

Is there any better way for this situation?

**Comment by EmergentOrder** [comment]
You could try using HBase rather than MySQL

**Comment by pferrel** [comment]
Does your method work? Have you noticed appreciable speedup?

**Comment by schon** [comment]
It works. 

1. Insert about 3,500,000 event data.
2. Start pio eventserver --verbose
3. run curl command like this.
  `http://<HOST>:7070/events.json?accessKey=<ACCESS_KEY>&entityId=2113110721001555235805&entityType=user&limit=1000`

#### First Query
- without index. It takes 4837 ms
```
  [SQL Execution]
   select id, event, entityType, entityId, targetEntityType, targetEntityId, properties, eventTime, eventTimeZone, tags, prId, creationTime, creationTimeZone from pio_event_27 where entityType = 'user' and entityId = '2113110721001555235805' order by eventTime asc limit 1000; (4837 ms)
```
  - with index . It takes 6 ms
```
  [SQL Execution]
   select id, event, entityType, entityId, targetEntityType, targetEntityId, properties, eventTime, eventTimeZone, tags, prId, creationTime, creationTimeZone from pio_event_15 where entityType = 'user' and entityId = '2113110721001555235805' order by eventTime asc limit 1000; (6 ms)
```

### Second Query 
- Both of them is fast from the second query if the query statement is the same.
- Probably `innodb_buffer_pool_size` in mysql config works from second query.

**Comment by pferrel** [comment]
Sounds like it's worth putting into the framework. I'm no SQL expert but making an enhancement request.

@schon could you create a pull request against the "develop" branch, that would be a big help.

**Comment by schon** [comment]
@pferrel Thank you for your consideration. I'll do it.

**Comment by EmergentOrder** [comment]
@schon don't see a PR for this, we'll be releasing 0.9.6 soon, so if you'd like to get it in, please submit. [thank you for your other PR btw!]

**Comment by schon** [comment]
Sorry to late. I have tested both mysql and postgresql.
To keep it backward compatibility, creating index is set configurable option.
Please check this PR.

Thanks
