### ISSUE TITLE
A performance problem about PredictionIO

### ISSUE THREAD

**Issue by YaozhengWang** [PredictionIO/PredictionIO#185]
When I import data in batch (about 100 million samples) into MyApp, the commands are as follows: 
cd MyRecommendation
python data/import_netflixdata.py --access_key $ACCESS_KEY
However,  the speed is very slow, could you please explain why?

**Comment by k4hoo** [comment]
it's because it's sending 1 record per HTTP request. The event server is better for recording real time event data.
You could try using batch import tool instead:
https://docs.prediction.io/datacollection/batchimport/

**Comment by schon** [comment]
Using `pio import` is the best way to speed up. 
Another option is to use asynchronous method.
http://pythonhosted.org/PredictionIO/predictionio.html#batch-import-data-with-eventclient

**Comment by YaozhengWang** [comment]
I imported 13GB data in batch by "pio import", it took about 50 minutes. was this normal?

**Comment by pferrel** [comment]
This should be taken to the user group
https://groups.google.com/forum/#!forum/predictionio-user

How many executors in total in your Spark cluster and are you using HDFS

**Comment by YaozhengWang** [comment]
one executor and I am using Hbase, not HDFS

**Comment by pferrel** [comment]
One executor generally means one read operator so this does not take advantage of Spark parallelism. Also you must use HDFS to import from multiple executors on multiple machines, HBase uses HDFS so you already have it running. In general horizontal scaling (distributed operations) relies on multiple executors, which can be set to the number of cores on your machine.

How much memory, what template?

Please move this to This should be taken to the user group
https://groups.google.com/forum/#!forum/predictionio-user

**Comment by YaozhengWang** [comment]
OK, Thanks
