### ISSUE TITLE
Weighted user actions

### ISSUE THREAD

**Issue by mklemme** [PredictionIO/PredictionIO#193]
I searched the docs and couldn't find anything about using user's meta information when posting actions to the PIO server. E.g.

User A is an admin.
User B is a normal user.

When User A rates Content A, their vote has 1.5x the weight as User B.

Another example could be Stackoverflow and their reputation system. A user with a higher ranking can sway the recommendations more than a newly signed up user.
 
Is this logic partially available? It looks like there's some documentation on pulling recommendations based on user's preferences, but nothing on weighted results.

**Comment by pferrel** [comment]
SO doesn't use their reputation system for recommendations they use the content of similar posts. 

There have been papers written about weighting the behavior of "experts" higher than others that indicates this might help. On the other hand look at how often everyday viewers of video on Rottentomatoes disagree with the professional reviewers. Usually similarity of taste trumps weight of user opinion and having more users in the pool will help find ones with similar taste. You would have to have a more "admins" than normal users to have a model that would cover as many items as the normal user.

To do something similar with the Universal Recommender you might add a property flag to items when some number of admins prefer the item. Then boost by the "admin-preferred": "true"  property. 

BTW can you use the PredictionIO Google group for this type of question? It's our preferred way to communicate with users.
