### ISSUE TITLE
PredictionIO starts about spark

### ISSUE THREAD

**Issue by YaozhengWang** [PredictionIO/PredictionIO#197]
The computational framework of PredictionIO relies on the spark, so I set SPARK_HOME = /app/hadoop/spark-1.5.2 in pio-env.sh. But when I start PredictionIO, the spark does not start, why? As shown in following picture:
![1](https://cloud.githubusercontent.com/assets/14865803/12161646/306fe046-b533-11e5-8d6b-f49f117d06a4.png)

**Comment by pferrel** [comment]
You have to start hdfs and spark by hand

**Comment by YaozhengWang** [comment]
when I start spark by hand, then I use pio train to train model, but the job don't execute in our spark cluster, while the model is still trained,  why?

**Comment by tom-chan** [comment]
You can use -- to separate arguments passed to spark, see https://docs.prediction.io/resources/faq/#engine-training for example.
