### ISSUE TITLE
Question: Overview of custom Data Store backends

### ISSUE THREAD

**Issue by tobilg** [PredictionIO/PredictionIO#201]
I read in the [docs](https://docs.prediction.io/system/anotherdatastore/) that custom Data Store backends can be implemented. My question is if there are already some implementations, namely for

* [InfluxDB](https://influxdata.com/time-series-platform/influxdb/)
* [Elasticsearch](https://www.elastic.co/products/elasticsearch)

I wasn't able to retrive any info on that via Google. Furthermore, I'm interested if there are any plany to support other backend for data storage from the project side.

Thanks in advance!

**Comment by k4hoo** [comment]
Yes. the code is here
https://github.com/PredictionIO/PredictionIO/tree/v0.9.5/data/src/main/scala/io/prediction/data/storage
for example, Elasticsearch is implemented for storing meta data.
and HBase is implemented for event data.

**Comment by tobilg** [comment]
Thanks for your reply. If I understand correctly, `HBase` and `JDBC` are the only currently supported Event Data stores. I'd like to leverage our existing Elasticsearch cluster for Event storage (we're already doing this, via Kafka). 

IMHO, it doesn't make sense (for us) to add another stack member like `HBase`. From the given code, I can't really judge how much effort it would be to take the existing ES Meta Data storage adapter and create an ES Event Data storage adapter. 

My question was also more related to if there *are* some other plugin implementations for Event Data storage, as there are none listed on the homepage, and a Google search is also not really fruitful...

**Comment by k4hoo** [comment]
correct. you need to implement the LEvents and PEvents trait for Elasticsearch

https://github.com/PredictionIO/PredictionIO/blob/v0.9.5/data/src/main/scala/io/prediction/data/storage/LEvents.scala
https://github.com/PredictionIO/PredictionIO/blob/v0.9.5/data/src/main/scala/io/prediction/data/storage/PEvents.scala
If you look at these traits, there are only a few functions you need to implement, basically write and read.

Example implementation for HBase and JDBC can be found in 
https://github.com/PredictionIO/PredictionIO/tree/v0.9.5/data/src/main/scala/io/prediction/data/storage/hbase
https://github.com/PredictionIO/PredictionIO/tree/v0.9.5/data/src/main/scala/io/prediction/data/storage/jdbc
(see XXXPEvents.scala and XXXLEvents.scala)

**Comment by tobilg** [comment]
Thanks a lot for the insights. I'll have a look.
