### ISSUE TITLE
v0.9.6 TLS error after initializing engine api

### ISSUE THREAD

**Issue by kakashit** [PredictionIO/PredictionIO#221]
I simply followed instructions at the quickstart in the documentations: https://docs.prediction.io/templates/recommendation/quickstart/

Everything is fine until the engine deployment:
```

[INFO] [Remoting] Starting remoting
[INFO] [Remoting] Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@172.17.0.2:42354]
[INFO] [Engine] Using persisted model
[INFO] [Engine] Custom-persisted model detected for algorithm org.template.recommendation.ALSAlgorithm
[WARN] [ALSModel] User factor does not have a partitioner. Prediction on individual records could be slow.
[WARN] [ALSModel] User factor is not cached. Prediction could be slow.
[WARN] [ALSModel] Product factor does not have a partitioner. Prediction on individual records could be slow.
[WARN] [ALSModel] Product factor is not cached. Prediction could be slow.
[INFO] [MasterActor] Undeploying any existing engine instance at https://0.0.0.0:8000
[WARN] [MasterActor] Nothing at https://0.0.0.0:8000
[INFO] [HttpListener] Bound to /0.0.0.0:8000
[INFO] [MasterActor] Engine is deployed and running. Engine API is live at https://0.0.0.0:8000.
```

After Engine API is initialized any request would fail with: 

`[ERROR] [OneForOneStrategy] Cannot support TLS_RSA_WITH_AES_256_CBC_SHA with currently installed providers`

I use java8 on ubuntu 14.04.

**Comment by kakashit** [comment]
I installed PredictionIO 0.9.5 instead of 0.9.6 and it worked fine. I guess there are some prerequisites on version 0.9.6 that is not mentioned in the docs (or I've missed it). I've also had issues with elasticsearch 2.x and later learned that elasticsearch 2.x is not supported. I didn't see this in the docs either.

**Comment by victorfu** [comment]
i have the same problem lol

**Comment by victorfu** [comment]
It seems oracle java causing the problem. If you are using oracle java 8, you need to install Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files 8. You can download jars at here: http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

There is also oracle java 7 version: http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html

Remember...!! put the jars in the $JRE_HOME/lib/security (not in $JDK_HOME/lib/security).

**Comment by kakashit** [comment]
Seems like this solves the problem. Thanks for sharing :+1:

**Comment by rhokstar** [comment]
This has also worked for me. I put the jars in here:

/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib

**Comment by gobert** [comment]
`/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib`
didnt't worked for me.

I get some improvements putting the jars in
`/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/security`

**Comment by hechemeljed** [comment]
I am working with PredictionIO v0.9.6.
First I had this error : 

> [ERROR] [OneForOneStrategy] Cannot support TLS_RSA_WITH_AES_256_CBC_SHA with currently installed providers

So I changed my Java 7 to Java 8 using:
`sudo apt-get install oracle-java8-unlimited-jce-policy`

After that I had this error : 

> [ERROR] [HttpServerConnection] Aborting encrypted connection to /127.0.0.1:49886 due to [SSLException:Unrecognized SSL message, plaintext connection?]

So I had to run my `cURL `queries on `HTTPS `and add `-k` .

**Comment by jamesward** [comment]
Since I installed Java 8 with brew, I installed the required JCE stuff with:

    brew cask install jce-unlimited-strength-policy

And then I had to visit https://localhost:8000 not `http` as the template stated.

**Comment by pferrel** [comment]
Hey guys, take this to the google group.

The Salesforce v0.9.6 forces TLS/SSL/HTPS and no SDKs or docs have been updated to address this change. If you don't want to deal with TLS either stay with 0.9.5 or upgrade to the ActionML fork here: https://github.com/actionml/cluster-setup/blob/master/install.md

**Comment by jamesward** [comment]
I think https for local dev is a bad default.  And most of the time https is handled by a front-end web server / load balancer in prod.  So I'm all for reverting this change.

**Comment by pferrel** [comment]
Agreed, I think this was done a bit prematurely. This should be an option, which Salesforce is supposed to be working on. Also not required for many production setups. BTW this is the only real feature of the Salesforce PIO v0.9.6 so no other reason to upgrade to it afaik. https://github.com/actionml/cluster-setup/blob/master/predictionio-by-actionml.md

Hopefully we get this fork nonsense sorted out soon too.

**Comment by ejzn** [comment]
Adding the oracle 8 policy JAR's to the lib/security folder in my JDK worked for me as well.
