### ISSUE TITLE
Error when try to Debug PIO TRAIN via Intellij IDEA

### ISSUE THREAD

**Issue by christianys14** [PredictionIO/PredictionIO#222]
i have installed prediction-io on ubuntu, so far i did successfull doing pio build, pio train and pio deploy via console prompt.

But i always fail to debug or simulate PIO TRAIN via intellij IDEA (using guide from https://docs.prediction.io/resources/intellij/) :

The Error are :

/usr/lib/jvm/java-8-openjdk-amd64/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:41364,suspend=y,server=n -Dspark.master=local -Dlog4j.configuration=file:/root/PredictionIO/conf/log4j.properties -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/icedtea-sound.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/management-agent.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/root/.sbt/boot/scala-2.10.5/lib/scala-library.jar:/home/zuki/Downloads/pio-assembly-0.9.5.jar:/home/zuki/Downloads/spark-assembly-1.5.1-hadoop2.6.0.jar:/home/zuki/Downloads/idea-IC-145.597.3/lib/idea_rt.jar io.prediction.workflow.CreateWorkflow --engine-id dummy --engine-version dummy --engine-variant engine.json
Connected to the target VM, address: '127.0.0.1:41364', transport: 'socket'
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/zuki/Downloads/pio-assembly-0.9.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/zuki/Downloads/spark-assembly-1.5.1-hadoop2.6.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Exception in thread "main" scala.reflect.internal.MissingRequirementError: object packYohan.RecommendationEngine not found.
	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
	at scala.reflect.internal.Mirrors$RootsBase.ensureModuleSymbol(Mirrors.scala:126)
	at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:161)
	at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:21)
	at io.prediction.workflow.WorkflowUtils$.getEngine(WorkflowUtils.scala:64)
	at io.prediction.workflow.CreateWorkflow$.liftedTree1$1(CreateWorkflow.scala:193)
	at io.prediction.workflow.CreateWorkflow$.main(CreateWorkflow.scala:192)
	at io.prediction.workflow.CreateWorkflow.main(CreateWorkflow.scala)
Disconnected from the target VM, address: '127.0.0.1:41364', transport: 'socket'
Process finished with exit code 1

Thanks in advance for help...

here's the link picture [https://16191547520272417628.googlegroups.com/attach/59d5d312d9db0/error_pio_train.png?part=0.1&view=1&vt=ANaJVrHSLn1w4eZ4r6mk_G5l9ZxSSIKbvs0qogiStLhUHsoalqeaIFLeqB_MpUS56G-9ssBXeIsmb9G08HLmY6YQo-oavMK7wSYFYw5yb9sXh7X_P47knS0](link)

**Comment by dszeto** [comment]
Continuing the thread in https://groups.google.com/forum/#!topic/predictionio-user/fEd-Cs3YXk4. Closing this.
