### ISSUE TITLE
Where can i See the changlog from 0.8.6 to 0.9.0?

### ISSUE THREAD

**Issue by kithokit** [PredictionIO/PredictionIO#54]

**Comment by k4hoo** [comment]
you can find upgrade instructions here 
http://docs.prediction.io/resources/upgrade/
and detail changes could be found here
https://predictionio.atlassian.net/projects/PDIO/versions/13400

**Comment by dszeto** [comment]
We are also updating release notes here: http://docs.prediction.io/release-notes/
Apologies for the working-in-progress.
