### ISSUE TITLE
Mac Re-Installation Break

### ISSUE THREAD

**Issue by KaroAntonio** [PredictionIO/PredictionIO#77]
Installing via the one line
bash -c "$(curl -s https://install.prediction.io/install.sh)" , accidentally ran install in bin.
Attempted to Re-Install with the same
bash -c "$(curl -s https://install.prediction.io/install.sh)" 
This broke the ./pio <arg> functionality

**Comment by xhudik** [comment]
well, I'm not a pio guy but I'd expect if you delete the previous installation(s), run a new one where you would specify the installation directory  you want - your problem disappear...
