### ISSUE TITLE
Use up of harddisk space

### ISSUE THREAD

**Issue by kithokit** [PredictionIO/PredictionIO#81]
Hi 

I found that prediction IO would generate a spark folder on /tmp i.e., ./spark-ddde0c32-fdbe-42be-a548-3f5f79c7921a/spark-44ec601a-c84d-489e-89b2-4f84082869e6 which occupy more than >100M each time. This files generated would not delete as long as I reboot machine.

This would use use my harddisk space easily while the actual event I received is not that much.

Should we delete it through cron job? What the purpose of that spark folder in /tmp.
```
tmp# du -Sh | sort -rh | head -n 10
104M	./spark-ffc1ff8f-ed6e-465c-be7d-a2fe2f10ccc8/spark-5afdfda7-5538-4bd9-b3e8-716d51b4e041
104M	./spark-fa050684-4c25-445d-bace-d62ba8218f74/spark-89e99fee-38fc-435a-9b42-d3908f5bf815
104M	./spark-eeb0aea2-a9e6-490b-868f-9d2018f47756/spark-d9c01201-4c17-4eee-90e9-c360f69c71e3
104M	./spark-eeadee40-8613-4eb8-9b15-470ba53a2885/spark-fb57b04a-97bd-4e81-bda4-3e78cea4d6bc
104M	./spark-e061ebe1-40e8-48d4-bb77-30c81d1c0853/spark-a496bab6-b0ee-4d8b-8386-d453820fd0c3/jars
104M	./spark-ddde0c32-fdbe-42be-a548-3f5f79c7921a/spark-44ec601a-c84d-489e-89b2-4f84082869e6
104M	./spark-d0129d2a-9727-47c7-a8f6-8998383b27c4/spark-65e3f45e-b487-474a-af19-161fcdb455bd
104M	./spark-c78543a7-031a-4942-a258-282c3cb15b15/spark-6ffc19b1-5cc9-44dd-8f96-a8cc6e4fd2b2
104M	./spark-c59fc89f-f870-467b-b7d2-768177d7ec6c/spark-9ff7301f-e251-46e8-9925-45ac48b4af24/jars
104M	./spark-c3ad7b83-9c93-41d7-bef0-a27a253cf1d9/spark-08cab9c5-df70-4a6d-b897-d58f385f9d14 
```

**Comment by dszeto** [comment]
These are generated by Apache Spark. Please refer to spark.local.dir in http://spark.apache.org/docs/1.2.1/configuration.html#application-properties.

Spark has no facility to remove these files automatically. Someone on the Spark mailing list has suggested the use of cron jobs to remove day or week-old files in spark.local.dir, depending on your training and deploy frequency.

**Comment by kithokit** [comment]
Yeah. Thanks for your prompt response.

I suggest that predictionIO can help to remove the last training folder if it won't affect the system.
Perhaps try to remove the old folder when we execute pio train. That's would reduce the error in the whole engine.

**Comment by dszeto** [comment]
Thanks for the suggestion. We don't really have control over that as Spark does not have a lot of management API. We will work with Databricks (the company behind Apache Spark) and see if they have a proper solution.

**Comment by randavidovitz** [comment]
From SoC we should resolve this within SPARK solution, I think its make sense.

**Comment by bhack** [comment]
It is documented at https://github.com/apache/spark/pull/5074

**Comment by pferrel** [comment]
It is dangerous to manage what Spark should manage. I think this should not be fixed in PIO. The referenced spark issue is only documentation but is seems to indicate that the only safe time to delete the files is when Spark is shutdown. 

We may want to document on the PIO site.  I'm at 15G and counting on my MBP.
